# Generated by Django 4.2.10 on 2024-02-21 19:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "1044_workflow_workflowaction_workflowtrigger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowaction",
            name="merge_permissions",
            field=models.BooleanField(default=True, verbose_name="merge permissions"),
        ),
    ]
